/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import spotlight from "../../src/plugins/spotlight/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    spotlight: spotlight,
  },
});
